<template>
    <Dialog
        v-model:visible="visible"
        modal
        header="Receipt"
        :style="getModalStyle(props.orderItems.length)"
        :closable="false"
        @keydown="handleKeydown"
    >
        <div class="space-y-4">
            <!-- Receipt Preview -->
            <div
                class="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto"
            >
                <ReceiptLayout
                    :business-logo="generalSettings.company_logo"
                    :business-name="
                        generalSettings.company_name ?? 'Quick Juan Restaurant'
                    "
                    :business-address="generalSettings.company_address"
                    :business-phone="generalSettings.company_phone"
                    :receipt-number="receiptData.receiptNumber"
                    :receipt-date="receiptData.date"
                    :table-info="receiptData.tableNumber"
                    :cashier-name="receiptData.cashierName"
                    :order-type="receiptData.orderType"
                    :order-items="receiptData.orderItems"
                    :subtotal="receiptData.subtotal"
                    :less-tax="receiptData.lessTax"
                    :less-discount="receiptData.lessDiscount"
                    :discount-name="receiptData.discountName"
                    :discount-type="receiptData.discountType"
                    :total-amount="receiptData.totalAmount"
                    :payment-info="receiptData.paymentInfo"
                    :tax-info="receiptData.taxInfo"
                    :receipt-footer="receiptFooter"
                    :footer-message="'Generated by Quick Juan POS System'"
                />
            </div>

            <div class="flex gap-3 pt-4 border-t">
                <button
                    type="button"
                    @click="handleClose"
                    class="flex-1 py-2 px-2 bg-gray-400 text-white rounded-md hover:bg-gray-500 transition-colors"
                >
                    Close
                </button>
                <button
                    ref="printButtonRef"
                    type="button"
                    @click="printReceipt"
                    class="flex-1 py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Print
                </button>
            </div>
        </div>
    </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from "vue";
import { Dialog } from "primevue";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import { route } from "ziggy-js";
import { router } from "@inertiajs/vue3";
import { useModalStyle } from "@/composables/useModalStyle";
import { thermalPrinter } from "@/Services/ThermalPrinterService";
import { useToast } from "primevue";

const props = defineProps<{
    visible: boolean;
    receiptData: any;
    orderItems: any[];
    receiptFooter: any;
    generalSettings: {
        company_name: string;
        company_address: string;
        company_phone: string;
        company_logo: string;
    };
    activeBranch?: any;
}>();

const emit = defineEmits<{
    "update:visible": [value: boolean];
}>();

const { getModalStyle } = useModalStyle();
const toast = useToast();

// Refs
const printButtonRef = ref<HTMLButtonElement>();

// Computed
const visible = computed({
    get: () => props.visible,
    set: (value) => emit("update:visible", value),
});

// Handle keyboard events
const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === "Enter") {
        event.preventDefault();
        printReceipt();
    } else if (event.key === "Escape") {
        event.preventDefault();
        visible.value = false;
    }
};

// Handle close modal
const handleClose = () => {
    router.visit(route("resto.tables"));
    visible.value = false;
};

// Print receipt using thermal printer service
const printReceipt = async () => {
    try {
        // Check if printer is connected
        if (!thermalPrinter.isConnected()) {
            // Try to connect to receipt printer
            const connected = await thermalPrinter.connectToPrinterType(
                "receipt"
            );
            if (!connected) {
                toast.add({
                    severity: "error",
                    summary: "Printer Not Connected",
                    detail: "Please connect to a thermal printer first.",
                    life: 5000,
                });
                return;
            }
        }

        // Format receipt data for thermal printer
        // Use branch info if available, otherwise use general settings
        const branchName =
            props.generalSettings.company_name ||
            props.activeBranch?.name ||
            "Quick Juan Restaurant";
        const branchDisplayName = props.activeBranch?.name;
        const branchAddress =
            props.activeBranch?.address ||
            props.generalSettings.company_address ||
            "";
        const branchPhone =
            props.activeBranch?.phone ||
            props.generalSettings.company_phone ||
            "";
        const receiptHeader = props.activeBranch?.receipt_headers || [];
        const receiptFooterData =
            props.activeBranch?.receipt_footer || props.receiptFooter;

        const thermalReceiptData = {
            storeName: branchName,
            branchName: branchDisplayName,
            storeAddress: branchAddress,
            storePhone: branchPhone,
            orderNumber: props.receiptData.receiptNumber,
            cashier: props.receiptData.cashierName || "",
            date: props.receiptData.date,
            time: props.receiptData.time,
            tableNumber:
                typeof props.receiptData.tableInfo === "object" &&
                props.receiptData.tableInfo?.name
                    ? props.receiptData.tableInfo.name
                    : typeof props.receiptData.tableNumber === "string"
                    ? props.receiptData.tableNumber
                    : "No Table",
            orderType: props.receiptData.orderType || "dine-in",
            items: props.receiptData.orderItems || [],
            subtotal: props.receiptData.subtotal || 0,
            lessTax: props.receiptData.lessTax || 0,
            lessDiscount: props.receiptData.lessDiscount || 0,
            total: props.receiptData.totalAmount || 0,
            payment: props.receiptData.paymentInfo
                ? {
                      method: props.receiptData.paymentInfo.method || "Cash",
                      amountPaid:
                          props.receiptData.paymentInfo.amount_paid || 0,
                      change: props.receiptData.paymentInfo.change || 0,
                  }
                : undefined,
            receiptHeader: receiptHeader,
            receiptFooter: receiptFooterData,
            footerMessage: "Generated by Quick Juan POS System",
        };

        // Print to thermal printer
        await thermalPrinter.printReceipt(thermalReceiptData);

        toast.add({
            severity: "success",
            summary: "Receipt Printed",
            detail: "Receipt has been sent to thermal printer successfully.",
            life: 3000,
        });

        // Close modal and redirect to tables after successful printing
        visible.value = false;
        router.visit(route("resto.tables"));
    } catch (error) {
        console.error("Print error:", error);
        toast.add({
            severity: "error",
            summary: "Print Error",
            detail:
                error instanceof Error
                    ? error.message
                    : "Failed to print receipt. Please try again.",
            life: 5000,
        });
    }
};

// Auto-focus print button when modal opens
watch(
    () => props.visible,
    (newVisible) => {
        if (newVisible) {
            nextTick(() => {
                printButtonRef.value?.focus();
            });
        }
    }
);
</script>
