<template>
    <Dialog
        v-model:visible="visible"
        modal
        header="Receipt"
        :style="getModalStyle(props?.receiptData.orderItems?.length)"
        :closable="false"
        @keydown="handleKeydown"
    >
        <div class="space-y-4">
            <!-- Receipt Preview -->
            <div
                class="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto"
            >
                <!-- :business-logo="generalSettings.company_logo" -->

                <ReceiptLayout
                    :store-name="page.props.company_info.company_name"
                    :branch="props.receiptData.branch"
                    :receipt-number="props.receiptData.invoice_no"
                    :receipt-date="props.receiptData.order_date"
                    :table-number="props.receiptData.table_number"
                    :cashier="props.receiptData.cashier"
                    :items="props.receiptData.order_items"
                    :totals="props.receiptData.totals"
                    :payment="props.receiptData.payment"
                    :receipt-footer="props.receiptData?.branch?.receipt_footer"
                    :footer-message="'Generated by Quick Juan POS System'"
                />
            </div>

            <div class="flex gap-3 pt-4 border-t">
                <button
                    type="button"
                    @click="handleClose"
                    class="flex-1 py-2 px-2 bg-gray-400 text-white rounded-md hover:bg-gray-500 transition-colors"
                >
                    Close
                </button>
                <button
                    ref="printButtonRef"
                    type="button"
                    @click="printReceipt"
                    class="flex-1 py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Print
                </button>
            </div>
        </div>
    </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from "vue";
import { Dialog } from "primevue";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import { route } from "ziggy-js";
import { router, usePage } from "@inertiajs/vue3";
import { useModalStyle } from "@/composables/useModalStyle";
import { thermalPrinter } from "@/Services/ThermalPrinterService";
import { useToast } from "primevue";

const props = defineProps<{
    visible: boolean;
    receiptData: any;
}>();

const page = usePage<any>();

const emit = defineEmits<{
    "update:visible": [value: boolean];
}>();

const { getModalStyle } = useModalStyle();
const toast = useToast();

// Refs
const printButtonRef = ref<HTMLButtonElement>();

// Computed
const visible = computed({
    get: () => props.visible,
    set: (value) => emit("update:visible", value),
});

// Handle keyboard events
const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === "Enter") {
        event.preventDefault();
        printReceipt();
    } else if (event.key === "Escape") {
        event.preventDefault();
        visible.value = false;
    }
};

// Handle close modal
const handleClose = () => {
    router.visit(route("resto.table-rooms"));
    visible.value = false;
};

// Print receipt using thermal printer service
const printReceipt = async () => {
    try {
        // Check if printer is connected
        if (!thermalPrinter.isConnected()) {
            // Try to connect to receipt printer
            const connected = await thermalPrinter.connectToPrinterType(
                "receipt"
            );
            if (!connected) {
                toast.add({
                    severity: "error",
                    summary: "Printer Not Connected",
                    detail: "Please connect to a thermal printer first.",
                    life: 5000,
                });
                return;
            }
        }

        const orderDate = new Date(
            props.receiptData.order_date || props.receiptData.created_at
        );
        const dateStr = orderDate.toLocaleDateString("en-US", {
            year: "numeric",
            month: "short",
            day: "numeric",
        });
        const timeStr = orderDate.toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
        });

        // Format receipt data for thermal printer
        const thermalReceiptData = {
            storeName: page.props.company_info.company_name,
            branch: props.receiptData.branch,
            orderNumber: props.receiptData.invoice_no,
            cashier: props.receiptData.cashier?.name,
            date: dateStr,
            time: timeStr,
            tableNumber: props.receiptData.table_number,
            items: props.receiptData.order_items || [],
            totals: props.receiptData.totals || 0,
            payment: props.receiptData.payment,
            receiptFooter: props.receiptData?.branch?.receipt_footer,
            footerMessage: "Generated by Quick Juan POS System",
        };

        // Print to thermal printer
        await thermalPrinter.printReceipt(thermalReceiptData);

        toast.add({
            severity: "success",
            summary: "Receipt Printed",
            detail: "Receipt has been sent to thermal printer successfully.",
            life: 3000,
        });

        // Close modal and redirect to tables after successful printing
        visible.value = false;
        router.visit(route("resto.tables"));
    } catch (error) {
        console.error("Print error:", error);
        toast.add({
            severity: "error",
            summary: "Print Error",
            detail:
                error instanceof Error
                    ? error.message
                    : "Failed to print receipt. Please try again.",
            life: 5000,
        });
    }
};

// Auto-focus print button when modal opens
watch(
    () => props.visible,
    (newVisible) => {
        if (newVisible) {
            nextTick(() => {
                printButtonRef.value?.focus();
            });
        }
    }
);
</script>
