<template>
    <Dialog
        v-model:visible="visible"
        modal
        header="Print Bill"
        :style="getModalStyle(props.orderItems.length)"
        :closable="false"
        @keydown="handleKeydown"
    >
        <div class="space-y-4">
            <!-- Bill Preview -->
            <div
                class="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto"
            >
                <BillLayout
                    :business-name="'Quick Juan Restaurant'"
                    :business-address="'123 Main Street, Makati City, Philippines'"
                    :business-phone="'(02) 123-4567'"
                    :bill-number="billData.billNumber"
                    :bill-date="billData.date"
                    :table-info="billData.tableInfo"
                    :cashier-name="billData.cashierName"
                    :order-type="billData.orderType"
                    :order-items="billData.orderItems"
                    :subtotal="billData.subtotal"
                    :less-tax="billData.lessTax"
                    :less-discount="billData.lessDiscount"
                    :discount-amount="billData.discountAmount"
                    :discount-name="billData.discountName"
                    :discount-type="billData.discountType"
                    :remove-tax="billData.removeTax"
                    :total-amount="billData.totalAmount"
                    :payment-info="billData.paymentInfo"
                    :bill-footer="billFooter"
                    :footer-message="'Generated by Quick Juan POS System'"
                />
            </div>

            <div class="flex gap-3 pt-4 border-t">
                <button
                    type="button"
                    @click="visible = false"
                    class="flex-1 py-2 px-2 bg-gray-400 text-white rounded-md hover:bg-gray-500 transition-colors"
                >
                    Close
                </button>
                <button
                    ref="printButtonRef"
                    type="button"
                    @click="printBill"
                    class="flex-1 py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Print
                </button>
            </div>
        </div>
    </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from "vue";
import { Dialog } from "primevue";
import BillLayout from "@/Components/BillLayout.vue";
import { useModalStyle } from "@/composables/useModalStyle";

const props = defineProps<{
    visible: boolean;
    billData: any;
    billFooter: any;
    orderItems: any[];
}>();

const emit = defineEmits<{
    "update:visible": [value: boolean];
}>();

const { getModalStyle } = useModalStyle();

// Refs
const printButtonRef = ref<HTMLButtonElement>();

// Computed
const visible = computed({
    get: () => props.visible,
    set: (value) => emit("update:visible", value),
});

// Handle keyboard events
const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === "Enter") {
        event.preventDefault();
        printBill();
    } else if (event.key === "Escape") {
        event.preventDefault();
        visible.value = false;
    }
};

// Print bill
const printBill = () => {
    // Get the BillLayout element from the modal
    const billElement = document.querySelector(
        ".bill-container"
    ) as HTMLElement;
    if (!billElement) {
        console.error("Bill element not found");
        return;
    }

    // Create a temporary print-friendly version
    const printContent = billElement.cloneNode(true) as HTMLElement;

    // Create hidden iframe for printing
    const iframe = document.createElement("iframe");
    iframe.style.display = "none";
    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
    if (iframeDoc) {
        iframeDoc.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Bill - ${props.billData.billNumber}</title>
                <style>
                    @media print {
                        body { margin: 0; }
                    }
                    body {
                        font-family: 'Courier New', monospace;
                        font-size: 12px;
                        line-height: 1.2;
                        margin: 0;
                        padding: 10px;
                        background: white;
                    }
                    .bill-container {
                        max-width: 300px;
                        margin: 0 auto;
                    }
                    .text-center { text-align: center; }
                    .text-right { text-align: right; }
                    .font-bold { font-weight: bold; }
                    .mb-2 { margin-bottom: 8px; }
                    .mb-4 { margin-bottom: 16px; }
                    .border-t { border-top: 1px solid #000; }
                    .border-b { border-bottom: 1px solid #000; }
                    .text-red-600 { color: #dc2626; }
                    .text-gray-500 { color: #6b7280; }
                    .text-gray-600 { color: #4b5563; }
                    .flex { display: flex; }
                    .justify-between { justify-content: space-between; }
                    .flex-1 { flex: 1; }
                    .ml-2 { margin-left: 8px; }
                    .mt-2 { margin-top: 8px; }
                    .mt-4 { margin-top: 16px; }
                    .mb-1 { margin-bottom: 4px; }
                    .pt-1 { padding-top: 4px; }
                    .border-dashed { border-style: dashed; border-width: 1px; }
                </style>
            </head>
            <body>
                ${printContent.outerHTML}
            </body>
            </html>
        `);
        iframeDoc.close();

        // Print and cleanup
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();

        // Remove iframe after printing
        setTimeout(() => {
            document.body.removeChild(iframe);
        }, 1000);
    }
};

// Auto-focus print button when modal opens
watch(
    () => props.visible,
    (newVisible) => {
        if (newVisible) {
            nextTick(() => {
                printButtonRef.value?.focus();
            });
        }
    }
);
</script>
