<template>
    <Dialog
        v-model:visible="visible"
        modal
        header="Receipt"
        :style="getModalStyle()"
        :closable="false"
        @keydown="handleKeydown"
    >
        <div class="space-y-4">
            <!-- Receipt Preview -->
            <div
                class="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto"
            >
                <ReceiptLayout
                    :business-name="'Quick Juan Restaurant'"
                    :business-address="'123 Main Street, Makati City, Philippines'"
                    :business-phone="'(02) 123-4567'"
                    :receipt-number="receiptData.receiptNumber"
                    :receipt-date="receiptData.date"
                    :table-number="receiptData.tableNumber"
                    :cashier-name="receiptData.cashierName"
                    :order-type="receiptData.orderType"
                    :order-items="receiptData.orderItems"
                    :subtotal="receiptData.subtotal"
                    :tax-amount="receiptData.taxAmount"
                    :discount-amount="receiptData.discountAmount"
                    :discount-name="receiptData.discountName"
                    :discount-type="receiptData.discountType"
                    :remove-tax="receiptData.removeTax"
                    :is-senior-discount="receiptData.isSeniorDiscount"
                    :total-amount="receiptData.totalAmount"
                    :payment-info="receiptData.paymentInfo"
                    :footer-message="'Generated by Quick Juan POS System'"
                />
            </div>

            <div class="flex gap-3 pt-4 border-t">
                <button
                    type="button"
                    @click="handleClose"
                    class="flex-1 py-2 px-2 bg-gray-400 text-white rounded-md hover:bg-gray-500 transition-colors"
                >
                    Close
                </button>
                <button
                    ref="printButtonRef"
                    type="button"
                    @click="printReceipt"
                    class="flex-1 py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Print
                </button>
            </div>
        </div>
    </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from "vue";
import { Dialog } from "primevue";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import { route } from "ziggy-js";
import { router } from "@inertiajs/vue3";

const props = defineProps<{
    visible: boolean;
    receiptData: any;
    orderItems: any[];
}>();

const emit = defineEmits<{
    "update:visible": [value: boolean];
}>();

// Refs
const printButtonRef = ref<HTMLButtonElement>();

// Computed
const visible = computed({
    get: () => props.visible,
    set: (value) => emit("update:visible", value),
});

// Get modal style based on receipt content
const getModalStyle = () => {
    const itemCount = props.orderItems.length;
    if (itemCount <= 3) {
        return { width: "30rem", maxHeight: "80vh" };
    } else if (itemCount <= 6) {
        return { width: "40rem", maxHeight: "85vh" };
    } else {
        return { width: "50rem", maxHeight: "90vh" };
    }
};

// Handle keyboard events
const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === "Enter") {
        event.preventDefault();
        printReceipt();
    } else if (event.key === "Escape") {
        event.preventDefault();
        visible.value = false;
    }
};

// Handle close modal
const handleClose = () => {
    router.visit(route("retail-cashier.tables"));
    visible.value = false;
};

// Print receipt
const printReceipt = () => {
    // Get the ReceiptLayout element from the modal
    const receiptElement = document.querySelector(
        ".receipt-container"
    ) as HTMLElement;
    if (!receiptElement) {
        console.error("Receipt element not found");
        return;
    }

    // Clone the receipt content
    const receiptClone = receiptElement.cloneNode(true) as HTMLElement;

    // Create a print-friendly popup window
    const printWindow = window.open("", "_blank", "width=400,height=600");
    if (printWindow) {
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Receipt - ${props.receiptData.receiptNumber}</title>
                <style>
                    @media print {
                        body { margin: 0; }
                        .no-print { display: none; }
                    }
                    body {
                        font-family: 'Courier New', monospace;
                        font-size: 12px;
                        line-height: 1.2;
                        margin: 0;
                        padding: 10px;
                        background: white;
                    }
                    .receipt-container {
                        max-width: 300px;
                        margin: 0 auto;
                    }
                    .text-center { text-align: center; }
                    .text-right { text-align: right; }
                    .font-bold { font-weight: bold; }
                    .mb-2 { margin-bottom: 8px; }
                    .mb-4 { margin-bottom: 16px; }
                    .border-t { border-top: 1px solid #000; }
                    .border-b { border-bottom: 1px solid #000; }
                    .text-red-600 { color: #dc2626; }
                    .text-gray-500 { color: #6b7280; }
                    .text-gray-600 { color: #4b5563; }
                    .text-xs { font-size: 10px; }
                    .flex { display: flex; }
                    .justify-between { justify-content: space-between; }
                    .flex-1 { flex: 1; }
                    .ml-2 { margin-left: 8px; }
                    .mt-2 { margin-top: 8px; }
                    .mt-4 { margin-top: 16px; }
                    .mb-1 { margin-bottom: 4px; }
                    .pt-1 { padding-top: 4px; }
                    .border-dashed { border-style: dashed; border-width: 1px; }
                </style>
            </head>
            <body>
                ${receiptClone.outerHTML}

                <div class="no-print text-center mt-4">
                    <button onclick="window.print()">Print</button>
                    <button onclick="window.close()">Close</button>
                </div>
            </body>
            </html>
        `);
        printWindow.document.close();
    }
};


// Auto-focus print button when modal opens
watch(
    () => props.visible,
    (newVisible) => {
        if (newVisible) {
            nextTick(() => {
                printButtonRef.value?.focus();
            });
        }
    }
);
</script>
