<template>
    <Dialog
        v-model:visible="visible"
        modal
        header="Receipt"
        :style="getModalStyle()"
        :closable="false"
        @keydown="handleKeydown"
    >
        <div class="space-y-4">
            <!-- Receipt Preview -->
            <div
                class="border border-gray-200 rounded-lg p-4 bg-gray-50 max-h-96 overflow-y-auto"
            >
                <ReceiptLayout
                    :business-name="'Quick Juan Restaurant'"
                    :business-address="'123 Main Street, Makati City, Philippines'"
                    :business-phone="'(02) 123-4567'"
                    :receipt-number="receiptData.receiptNumber"
                    :receipt-date="receiptData.date"
                    :table-number="receiptData.tableNumber"
                    :cashier-name="receiptData.cashierName"
                    :order-type="receiptData.orderType"
                    :order-items="receiptData.orderItems"
                    :subtotal="receiptData.subtotal"
                    :tax-amount="receiptData.taxAmount"
                    :discount-amount="receiptData.discountAmount"
                    :discount-name="receiptData.discountName"
                    :discount-type="receiptData.discountType"
                    :remove-tax="receiptData.removeTax"
                    :is-senior-discount="receiptData.isSeniorDiscount"
                    :total-amount="receiptData.totalAmount"
                    :payment-info="receiptData.paymentInfo"
                    :footer-message="'Generated by Quick Juan POS System'"
                />
            </div>

            <div class="flex gap-3 pt-4 border-t">
                <button
                    type="button"
                    @click="visible = false"
                    class="flex-1 py-2 px-2 bg-gray-400 text-white rounded-md hover:bg-gray-500 transition-colors"
                >
                    Close
                </button>
                <button
                    ref="printButtonRef"
                    type="button"
                    @click="printReceipt"
                    class="flex-1 py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                    Print
                </button>
            </div>
        </div>
    </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, watch } from "vue";
import { Dialog } from "primevue";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";

const props = defineProps<{
    visible: boolean;
    receiptData: any;
    orderItems: any[];
}>();

const emit = defineEmits<{
    "update:visible": [value: boolean];
}>();

// Refs
const printButtonRef = ref<HTMLButtonElement>();

// Computed
const visible = computed({
    get: () => props.visible,
    set: (value) => emit("update:visible", value),
});

// Get modal style based on receipt content
const getModalStyle = () => {
    const itemCount = props.orderItems.length;
    if (itemCount <= 3) {
        return { width: "30rem", maxHeight: "80vh" };
    } else if (itemCount <= 6) {
        return { width: "40rem", maxHeight: "85vh" };
    } else {
        return { width: "50rem", maxHeight: "90vh" };
    }
};

// Handle keyboard events
const handleKeydown = (event: KeyboardEvent) => {
    if (event.key === "Enter") {
        event.preventDefault();
        printReceipt();
    } else if (event.key === "Escape") {
        event.preventDefault();
        visible.value = false;
    }
};

// Print receipt
const printReceipt = () => {
    // Create a print-friendly popup window
    const printWindow = window.open("", "_blank", "width=400,height=600");
    if (printWindow) {
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Receipt - ${props.receiptData.receiptNumber}</title>
                <style>
                    @media print {
                        body { margin: 0; }
                        .no-print { display: none; }
                    }
                    body {
                        font-family: 'Courier New', monospace;
                        font-size: 12px;
                        line-height: 1.2;
                        margin: 0;
                        padding: 10px;
                        background: white;
                    }
                    .receipt-container {
                        max-width: 300px;
                        margin: 0 auto;
                    }
                    .text-center { text-align: center; }
                    .text-right { text-align: right; }
                    .font-bold { font-weight: bold; }
                    .mb-2 { margin-bottom: 8px; }
                    .mb-4 { margin-bottom: 16px; }
                    .border-t { border-top: 1px solid #000; padding-top: 8px; }
                    .border-b { border-bottom: 1px solid #000; padding-bottom: 8px; }
                </style>
            </head>
            <body>
                <div class="receipt-container">
                    <div class="text-center mb-4">
                        <div class="font-bold">Quick Juan Restaurant</div>
                        <div>123 Main Street, Makati City, Philippines</div>
                        <div>(02) 123-4567</div>
                    </div>

                    <div class="border-b mb-2">
                        <div>Receipt: ${props.receiptData.receiptNumber}</div>
                        <div>Date: ${new Date(
                            props.receiptData.date
                        ).toLocaleString()}</div>
                        <div>Table: ${
                            props.receiptData.tableNumber || "N/A"
                        }</div>
                        <div>Cashier: ${props.receiptData.cashierName}</div>
                        <div>Order Type: ${props.receiptData.orderType}</div>
                    </div>

                    <div class="mb-2">
                        ${props.receiptData.orderItems
                            .map(
                                (item) => `
                            <div class="mb-1">
                                <div>${item.quantity}x ${
                                    item.product_name
                                }</div>
                                ${
                                    item.selected_options &&
                                    item.selected_options.length > 0
                                        ? item.selected_options
                                              .map(
                                                  (opt: any) =>
                                                      `<div class="text-right">+ ${opt.name}</div>`
                                              )
                                              .join("")
                                        : ""
                                }
                                <div class="text-right">₱${item.price}</div>
                            </div>
                        `
                            )
                            .join("")}
                    </div>

                    <div class="border-t">
                        <div class="text-right mb-1">Subtotal: ₱${props.receiptData.subtotal.toFixed(
                            2
                        )}</div>
                        ${
                            props.receiptData.discountAmount > 0
                                ? `<div class="text-right mb-1">Discount: -₱${props.receiptData.discountAmount.toFixed(
                                      2
                                  )}</div>`
                                : ""
                        }
                        <div class="text-right mb-1">Tax (12%): ₱${props.receiptData.taxAmount.toFixed(
                            2
                        )}</div>
                        <div class="text-right font-bold">Total: ₱${props.receiptData.totalAmount.toFixed(
                            2
                        )}</div>
                    </div>

                    ${
                        props.receiptData.paymentInfo
                            ? `
                        <div class="border-t mt-2">
                            <div class="text-right mb-1">Paid: ₱${
                                props.receiptData.paymentInfo.amount_paid
                            }</div>
                            <div class="text-right mb-1">Change: ₱${props.receiptData.paymentInfo.change.toFixed(
                                2
                            )}</div>
                            <div class="text-right">Method: ${
                                props.receiptData.paymentInfo.method
                            }</div>
                        </div>
                    `
                            : ""
                    }

                    <div class="text-center mt-4">
                        <div>Thank you for your business!</div>
                        <div>Generated by Quick Juan POS System</div>
                    </div>
                </div>

                <div class="no-print text-center mt-4">
                    <button onclick="window.print()">Print</button>
                    <button onclick="window.close()">Close</button>
                </div>
            </body>
            </html>
        `);
        printWindow.document.close();
    }
};

// Auto-focus print button when modal opens
watch(
    () => props.visible,
    (newVisible) => {
        if (newVisible) {
            nextTick(() => {
                printButtonRef.value?.focus();
            });
        }
    }
);
</script>
