<template>
    <div class="min-h-screen bg-gray-100 py-8">
        <div class="max-w-4xl mx-auto px-4">
            <div class="bg-white rounded-lg shadow-lg p-6">
                <div class="flex justify-between items-center mb-6">
                    <h1 class="text-2xl font-bold text-gray-900">
                        Receipt #{{ receiptId }}
                    </h1>
                    <button
                        @click="printReceipt"
                        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors"
                    >
                        Print Receipt
                    </button>
                </div>

                <!-- Receipt Preview -->
                <div class="flex justify-center mb-6">
                    <div class="bg-gray-50 p-4 rounded-lg border">
                        <ReceiptLayout
                            :business-name="businessInfo.name"
                            :business-address="businessInfo.address"
                            :business-phone="businessInfo.phone"
                            :receipt-number="receiptData.receiptNumber"
                            :receipt-date="receiptData.date"
                            :table-number="receiptData.tableNumber"
                            :cashier-name="receiptData.cashierName"
                            :order-type="receiptData.orderType"
                            :order-items="receiptData.orderItems"
                            :subtotal="receiptData.subtotal"
                            :tax-amount="receiptData.taxAmount"
                            :discount-amount="receiptData.discountAmount"
                            :total-amount="receiptData.totalAmount"
                            :payment-info="receiptData.paymentInfo"
                            :footer-message="businessInfo.footerMessage"
                        />
                    </div>
                </div>

                <!-- Back Button -->
                <div class="flex justify-center">
                    <button
                        @click="goBack"
                        class="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition-colors"
                    >
                        ← Back to Cashier
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { router, usePage } from "@inertiajs/vue3";
import { route } from "ziggy-js";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import PageProps from "@/Types/PageProps";

const props = defineProps<{
    receiptId: string;
}>();

const page = usePage<PageProps>();

// Business information
const businessInfo = ref({
    name: "Quick Juan Restaurant",
    address: "123 Main Street, Makati City, Philippines",
    phone: "(02) 123-4567",
    footerMessage: "Generated by Quick Juan POS System",
});

// Receipt data - In a real app, this would be fetched from the server
const receiptData = ref({
    receiptNumber: `RCP-${props.receiptId}`,
    date: new Date().toISOString(),
    tableNumber: "Table 5",
    cashierName: page.props?.auth?.user?.name,
    orderType: "dine-in",
    orderItems: [] as any[],
    subtotal: 0,
    taxAmount: 0,
    discountAmount: 0,
    totalAmount: 0,
    paymentInfo: null as any,
});

// Load sample data (in real app, fetch from API)
const loadReceiptData = () => {
    receiptData.value.orderItems = [
        {
            id: 1,
            product_name: "Chicken Joy",
            quantity: 2,
            unit_price: 85.0,
            price: 170.0,
            selected_options: [
                { id: 1, name: "Extra Rice", price: 15.0 },
                { id: 2, name: "Regular Drink", price: 20.0 },
            ],
            discount: 0,
        },
        {
            id: 2,
            product_name: "Tuna Pie",
            quantity: 1,
            unit_price: 45.0,
            price: 45.0,
            selected_options: [],
            discount: 5.0,
        },
    ];

    // Calculate totals
    const subtotal = receiptData.value.orderItems.reduce(
        (sum, item) => sum + item.price,
        0
    );
    const discountAmount = receiptData.value.orderItems.reduce(
        (sum, item) => sum + (item.discount || 0),
        0
    );
    const discountedSubtotal = subtotal - discountAmount;
    const taxAmount = discountedSubtotal * 0.12; // 12% VAT
    const totalAmount = discountedSubtotal + taxAmount;

    receiptData.value.subtotal = subtotal;
    receiptData.value.discountAmount = discountAmount;
    receiptData.value.taxAmount = taxAmount;
    receiptData.value.totalAmount = totalAmount;

    receiptData.value.paymentInfo = {
        amount_paid: 350.0,
        change: 350.0 - totalAmount,
        method: "Cash",
    };
};

// Print function
const printReceipt = () => {
    window.print();
};

// Go back to cashier
const goBack = () => {
    router.visit(route("retail-cashier.index"));
};

onMounted(() => {
    loadReceiptData();
});
</script>

<style>
@media print {
    body * {
        visibility: hidden;
    }
    .receipt-container,
    .receipt-container * {
        visibility: visible;
    }
    .receipt-container {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        max-width: none;
    }
}
</style>
