<template>
    <!-- Full page layout when used as standalone page -->
    <div v-if="!embedded" class="min-h-screen bg-gray-100 py-8">
        <div class="max-w-4xl mx-auto px-4">
            <div class="bg-white rounded-lg shadow-lg p-6">
                <div class="flex justify-between items-center mb-6">
                    <h1 class="text-2xl font-bold text-gray-900">
                        Receipt #{{ receiptId }}
                    </h1>
                    <div class="flex gap-2">
                        <button
                            @click="printReceipt"
                            class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors"
                        >
                            Print Receipt
                        </button>
                        <button
                            @click="printThermal"
                            class="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 transition-colors"
                        >
                            Print (Thermal)
                        </button>
                    </div>
                </div>

                <!-- Receipt Preview -->
                <div class="flex justify-center mb-6">
                    <div class="bg-gray-50 p-4 rounded-lg border">
                        <ReceiptLayout
                            :business-logo="generalSettings.company_logo"
                            :business-name="
                                generalSettings.company_name ?? 'QuickJuan POS'
                            "
                            :business-address="generalSettings.company_address"
                            :business-phone="generalSettings.company_phone"
                            :receipt-number="receiptData.receiptNumber"
                            :receipt-date="receiptData.date"
                            :table-info="receiptData.tableNumber"
                            :cashier-name="receiptData.cashierName"
                            :order-type="receiptData.orderType"
                            :order-items="receiptData.orderItems"
                            :subtotal="receiptData.subtotal"
                            :less-tax="receiptData.lessTax"
                            :less-discount="receiptData.lessDiscount"
                            :discount-name="receiptData.discountName"
                            :discount-type="receiptData.discountType"
                            :total-amount="receiptData.totalAmount"
                            :payment-info="receiptData.paymentInfo"
                            :tax-info="receiptData.taxInfo"
                            :receipt-footer="receiptFooter"
                            :footer-message="'Generated by Quick Juan POS System'"
                        />
                    </div>
                </div>

                <!-- Back Button -->
                <div class="flex justify-center">
                    <button
                        @click="goBack"
                        class="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition-colors"
                    >
                        ← Back to Cashier
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Embedded layout when used as component -->
    <div v-else>
        <ReceiptLayout
            :business-logo="generalSettings?.company_logo"
            :business-name="generalSettings?.company_name ?? 'QuickJuan POS'"
            :business-address="generalSettings?.company_address"
            :business-phone="generalSettings?.company_phone"
            :receipt-number="receiptData.receiptNumber"
            :receipt-date="receiptData.date"
            :table-info="receiptData.tableNumber"
            :cashier-name="receiptData.cashierName"
            :order-type="receiptData.orderType"
            :order-items="receiptData.orderItems"
            :subtotal="receiptData.subtotal"
            :less-tax="receiptData.lessTax"
            :less-discount="receiptData.lessDiscount"
            :discount-name="receiptData.discountName"
            :discount-type="receiptData.discountType"
            :total-amount="receiptData.totalAmount"
            :payment-info="receiptData.paymentInfo"
            :tax-info="receiptData.taxInfo"
            :receipt-footer="receiptFooter"
            footer-message=""
        />
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, computed } from "vue";
import { router } from "@inertiajs/vue3";
import { route } from "ziggy-js";
import axios from "axios";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import { thermalPrinter } from "@/Services/ThermalPrinterService";

const props = defineProps<{
    receiptId: string;
    embedded?: boolean;
    orderData?: any;
    receiptFooter: any;
    generalSettings: {
        company_name: string;
        company_address: string;
        company_phone: string;
        company_logo: string;
    };
}>();

// Receipt data - In a real app, this would be fetched from the server
const receiptData = ref({
    receiptNumber: "001234",
    date: new Date().toISOString(),
    tableNumber: "",
    cashierName: "",
    orderType: "",
    orderItems: [] as any[],
    subtotal: 0,
    lessTax: 0,
    lessDiscount: 0,
    discountName: null as string | null,
    discountType: null as string | null,
    totalAmount: 0,
    paymentInfo: null as any,
    taxInfo: null as any,
});

// Load data - either from props or fetch from API
const loadReceiptData = async () => {
    if (props.embedded && props.orderData) {
        // Use data from props when embedded
        const order = props.orderData;
        const orderItems = order.order_items || [];

        // Map orderItems to include name from product and discount
        getReceiptData(order, orderItems);
    } else {
        // Fetch order data for standalone page
        try {
            const response = await axios.get(
                route("transactions.api.orders.show", props.receiptId)
            );
            const order = response.data;
            if (order) {
                const orderItems = order.order_items || [];

                getReceiptData(order, orderItems);
            }
        } catch (error) {
            console.error("Error fetching order:", error);
        }
    }
};

const getReceiptData = (order: any, orderItemsParam: any) => {
    // Handle both old flat structure and new grouped structure
    let mappedOrderItems: any[] = [];

    if (Array.isArray(orderItemsParam) && orderItemsParam.length > 0) {
        // New grouped structure: array of {orderId, orderType, orderItems}
        if (orderItemsParam[0].orderItems) {
            // Keep the grouped structure for ReceiptLayout
            mappedOrderItems = orderItemsParam.map((group: any) => ({
                orderId: group.orderId,
                orderType: group.orderType,
                orderItems: group.orderItems.map((item: any) => ({
                    ...item,
                    name:
                        item.description ||
                        item.product?.name ||
                        "Unnamed item",
                    discount:
                        item.discount_amount ||
                        (item.discount === "N/A" ? 0 : item.discount),
                    less_tax: parseFloat(String(item.lessTax || 0)),
                    quantity: parseFloat(String(item.quantity || 0)),
                    price: parseFloat(String(item.price || 0)),
                    amount: parseFloat(String(item.amount || 0)),
                })),
            }));
        } else {
            // Old flat structure - wrap in grouped format for compatibility
            mappedOrderItems = [
                {
                    orderId: null,
                    orderType: "dine-in",
                    orderItems: orderItemsParam.map((item: any) => ({
                        ...item,
                        name: item.product?.name || "Unnamed item",
                        discount: item.discount_amount || 0,
                        description:
                            item.name || item.product?.name || "Unnamed item",
                        quantity: parseFloat(String(item.quantity || 0)),
                        price: parseFloat(String(item.price || 0)),
                        amount: parseFloat(String(item.amount || 0)),
                        less_tax: parseFloat(String(item.less_tax || 0)),
                    })),
                },
            ];
        }
    }

    // Use order.totals if available (new structure), otherwise calculate
    let totalAmount: number;
    let lessTaxTotal: number;
    let lessDiscountTotal: number;
    let amount: number;

    if (order.totals) {
        // New API structure with totals object
        amount = parseFloat(String(order.totals.total_amount || 0));
        lessTaxTotal = parseFloat(String(order.totals.less_tax || 0));
        lessDiscountTotal = parseFloat(String(order.totals.less_discount || 0));
        totalAmount = parseFloat(
            String(order.totals.total_due || order.totals.total_amount || 0)
        );
    } else {
        // Old structure - calculate from items
        const flattenedItems = mappedOrderItems.flatMap(
            (group: any) => group.orderItems
        );
        amount = flattenedItems.reduce(
            (sum: number, item: any) =>
                sum + Number(item.quantity * item.price || 0),
            0
        );
        lessTaxTotal = flattenedItems.reduce(
            (sum: number, item: any) => sum + Number(item.less_tax || 0),
            0
        );
        lessDiscountTotal = flattenedItems.reduce(
            (sum: number, item: any) => sum + Number(item.discount_amount || 0),
            0
        );
        totalAmount = amount - (lessTaxTotal + lessDiscountTotal);
    }

    const paymentInfo = order.payment || {
        amount_paid: order.amount_tendered || null,
        total_amount: order.total_due || null,
        change: order.amount_tendered - order.total_due || null,
    };

    // Calculate tax info from order items
    const flattenedItems = mappedOrderItems.flatMap(
        (group: any) => group.orderItems
    );
    const calculatedTaxInfo = flattenedItems.reduce(
        (acc: any, item: any) => {
            acc.vatableSales += Number(item.vatable_sales) || 0;
            acc.nonVatableSales += Number(item.non_vat_sales) || 0;
            acc.vatExemptSales += Number(item.vat_exempt_sales) || 0;
            acc.vatAmount += Number(item.vat_amount) || 0;
            return acc;
        },
        {
            vatableSales: 0,
            nonVatableSales: 0,
            vatExemptSales: 0,
            vatAmount: 0,
        }
    );

    // Use order totals if available, otherwise use calculated tax info
    const taxInfo = order.totals || calculatedTaxInfo;

    receiptData.value.receiptNumber = `RCP-${order.id}`;
    receiptData.value.date = order.order_date || order.created_at;
    receiptData.value.tableNumber = order.table_number || "N/A";
    receiptData.value.cashierName = order.cashier?.name || "Unknown";
    receiptData.value.orderType = null; // Order type is per item in new structure
    receiptData.value.orderItems = mappedOrderItems;
    receiptData.value.subtotal = parseFloat(
        String(order.totals?.total_amount || 0)
    );
    receiptData.value.lessTax = parseFloat(String(order.totals?.less_tax || 0));
    receiptData.value.lessDiscount = parseFloat(
        String(order.totals?.less_discount || 0)
    );
    receiptData.value.totalAmount = parseFloat(
        String(order.totals?.total_due || order.totals?.total_amount || 0)
    );
    receiptData.value.paymentInfo = order.payment || order.meta || null;
    receiptData.value.taxInfo = taxInfo;
};

// Print function
const printReceipt = () => {
    window.print();
};

// Thermal printer function
const printThermal = async () => {
    if (!receiptData.value) return;

    try {
        // Load printer config first
        const printerConfig = await thermalPrinter.loadPrinterConfig("receipt");

        if (!printerConfig) {
            alert(
                "No printer configuration found. Please configure a printer first."
            );
            return;
        }

        // Check if already connected
        const isConnected = thermalPrinter.isConnected();

        if (isConnected) {
            // Already connected - print immediately
            await printThermalReceipt();
        } else {
            // Not connected - try to connect first
            try {
                const connected = await thermalPrinter.connectToPrinter(
                    printerConfig
                );

                if (connected) {
                    await printThermalReceipt();
                } else {
                    alert("Failed to connect to printer. Please try again.");
                }
            } catch (error: any) {
                if (
                    error.message?.includes("User cancelled") ||
                    error.name === "NotFoundError"
                ) {
                    console.log("User cancelled printer connection");
                    return;
                }
                console.error("Connection/print failed:", error);
                alert("Error connecting to printer. Please try again.");
            }
        }
    } catch (error) {
        console.error("Failed to load printer config:", error);
        alert("Failed to load printer configuration.");
    }
};

// Helper function to build thermal receipt data from receiptData
const printThermalReceipt = async () => {
    try {
        // Flatten grouped order items for thermal printer
        const flattenedItems =
            receiptData.value.orderItems?.flatMap((group: any) =>
                group.orderItems.map((item: any) => ({
                    name: item.description || item.name || "Item",
                    quantity: parseFloat(String(item.quantity || 0)),
                    price: parseFloat(String(item.price || 0)),
                    amount: parseFloat(String(item.amount || 0)),
                    selectedOptions:
                        item.modifiers?.map((mod: string) => ({
                            name: mod,
                            price: 0,
                        })) || [],
                    less_tax: parseFloat(
                        String(item.less_tax || item.lessTax || 0)
                    ),
                    discount:
                        item.discount === "N/A"
                            ? 0
                            : parseFloat(
                                  String(
                                      item.discount_amount || item.discount || 0
                                  )
                              ),
                    orderType: item.orderType || "dine-in",
                }))
            ) || [];

        // Build receipt data in the format expected by ThermalPrinterService
        const thermalData: any = {
            storeName: generalSettings.company_name || "Quick Juan POS",
            storeAddress: generalSettings.company_address || "",
            storePhone: generalSettings.company_phone || "",
            orderNumber: receiptData.value.receiptNumber || "",
            cashier: receiptData.value.cashierName || "Unknown",
            date: receiptData.value.date || new Date().toISOString(),
            time: "",
            tableNumber: receiptData.value.tableNumber || null,
            items: flattenedItems,
            subtotal: receiptData.value.subtotal || 0,
            lessTax: receiptData.value.lessTax || 0,
            lessDiscount: receiptData.value.lessDiscount || 0,
            total: receiptData.value.totalAmount || 0,
            payment: receiptData.value.paymentInfo || {
                method: "Cash",
                amountPaid: 0,
                change: 0,
            },
            receiptFooter: receiptFooter,
            footerMessage: "Generated by Quick Juan POS System",
        };

        await thermalPrinter.printReceipt(thermalData);
        console.log("✅ Receipt printed successfully");
    } catch (error) {
        console.error("Failed to print receipt:", error);
        alert("Error printing receipt. Please try again.");
    }
};

// Go back to cashier
const goBack = () => {
    router.visit(route("resto.index"));
};

onMounted(() => {
    loadReceiptData();

    // Auto-print if print parameter is present
    if (new URLSearchParams(window.location.search).get("print") === "1") {
        // Small delay to ensure content is loaded
        setTimeout(() => {
            window.print();
        }, 500);
    }
});

watch(
    () => props.orderData,
    (newOrderData) => {
        if (newOrderData) {
            loadReceiptData();
        }
    },
    { immediate: false }
);
</script>

<style>
@media print {
    body * {
        visibility: hidden;
    }
    .receipt-container,
    .receipt-container * {
        visibility: visible;
    }
    .receipt-container {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        max-width: none;
    }
}
</style>
