<template>
    <!-- Full page layout when used as standalone page -->
    <div v-if="!embedded" class="min-h-screen bg-gray-100 py-8">
        <div class="max-w-4xl mx-auto px-4">
            <div class="bg-white rounded-lg shadow-lg p-6">
                <div class="flex justify-between items-center mb-6">
                    <h1 class="text-2xl font-bold text-gray-900">
                        Receipt #{{ receiptId }}
                    </h1>
                    <button
                        @click="printReceipt"
                        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors"
                    >
                        Print Receipt
                    </button>
                </div>

                <!-- Receipt Preview -->
                <div class="flex justify-center mb-6">
                    <div class="bg-gray-50 p-4 rounded-lg border">
                        <ReceiptLayout
                            :business-name="businessInfo.name"
                            :business-address="businessInfo.address"
                            :business-phone="businessInfo.phone"
                            :receipt-number="receiptData.receiptNumber"
                            :receipt-date="receiptData.date"
                            :table-number="receiptData.tableNumber"
                            :cashier-name="receiptData.cashierName"
                            :order-type="receiptData.orderType"
                            :order-items="receiptData.orderItems"
                            :subtotal="receiptData.subtotal"
                            :tax-amount="receiptData.taxAmount"
                            :discount-amount="receiptData.discountAmount"
                            :total-amount="receiptData.totalAmount"
                            :payment-info="receiptData.paymentInfo"
                            :footer-message="businessInfo.footerMessage"
                            :receipt-footer="null"
                        />
                    </div>
                </div>

                <!-- Back Button -->
                <div class="flex justify-center">
                    <button
                        @click="goBack"
                        class="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition-colors"
                    >
                        ← Back to Cashier
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Embedded layout when used as component -->
    <div v-else>
        <ReceiptLayout
            :business-name="businessInfo.name"
            :business-address="businessInfo.address"
            :business-phone="businessInfo.phone"
            :receipt-number="receiptData.receiptNumber"
            :receipt-date="receiptData.date"
            :table-number="receiptData.tableNumber"
            :cashier-name="receiptData.cashierName"
            :order-type="receiptData.orderType"
            :order-items="receiptData.orderItems"
            :subtotal="receiptData.subtotal"
            :tax-amount="receiptData.taxAmount"
            :discount-amount="receiptData.discountAmount"
            :total-amount="receiptData.totalAmount"
            :payment-info="receiptData.paymentInfo"
            :footer-message="businessInfo.footerMessage"
            :receipt-footer="null"
            :embedded="true"
        />
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { router, usePage } from "@inertiajs/vue3";
import { route } from "ziggy-js";
import axios from "axios";
import ReceiptLayout from "@/Components/ReceiptLayout.vue";
import PageProps from "@/Types/PageProps";

const props = defineProps<{
    receiptId: string;
    embedded?: boolean;
    orderData?: any;
}>();

const page = usePage<PageProps>();

// Business information
const businessInfo = ref({
    name: "Quick Juan Restaurant",
    address: "123 Main Street, Makati City, Philippines",
    phone: "(02) 123-4567",
    footerMessage: "Generated by Quick Juan POS System",
});

// Receipt data - In a real app, this would be fetched from the server
const receiptData = ref({
    receiptNumber: `RCP-${props.receiptId}`,
    date: new Date().toISOString(),
    tableNumber: "Table 5",
    cashierName: page.props?.auth?.user?.name,
    orderType: "dine-in",
    orderItems: [] as any[],
    subtotal: 0,
    taxAmount: 0,
    discountAmount: 0,
    totalAmount: 0,
    paymentInfo: null as any,
});

// Load data - either from props or fetch from API
const loadReceiptData = async () => {
    if (props.embedded && props.orderData) {
        // Use data from props when embedded
        const order = props.orderData;
        const orderItems = order.order_items || [];

        // Map orderItems to include name from product and discount
        const mappedOrderItems = orderItems.map((item: any) => ({
            ...item,
            name: item.product?.name || "Unnamed item",
            discount: item.discount_amount || 0,
        }));

        // Calculate totals
        const subtotal = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.sub_total || 0), 0);
        const taxAmount = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.less_tax || 0), 0);
        const discountAmount = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.discount_amount || 0), 0);
        const totalAmount = subtotal + taxAmount - discountAmount;

        receiptData.value.receiptNumber = `RCP-${order.id}`;
        receiptData.value.date = order.created_at;
        receiptData.value.tableNumber = order.table_room?.name || "N/A";
        receiptData.value.cashierName = order.cashier?.name || "Unknown";
        receiptData.value.orderType = (order as any).order_type || "dine-in";
        receiptData.value.orderItems = mappedOrderItems;
        receiptData.value.subtotal = subtotal;
        receiptData.value.taxAmount = taxAmount;
        receiptData.value.discountAmount = discountAmount;
        receiptData.value.totalAmount = totalAmount;
        receiptData.value.paymentInfo = (order as any).payment_info || null;
    } else {
        // Fetch order data for standalone page
        try {
            const response = await axios.get(route('transactions.api.orders.show', props.receiptId));
            const order = response.data;
            if (order) {
                const orderItems = order.order_items || [];

                // Map orderItems to include name from product and discount
                const mappedOrderItems = orderItems.map((item: any) => ({
                    ...item,
                    name: item.product?.name || "Unnamed item",
                    discount: item.discount_amount || 0,
                }));

                // Calculate totals
                const subtotal = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.sub_total || 0), 0);
                const taxAmount = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.less_tax || 0), 0);
                const discountAmount = mappedOrderItems.reduce((sum: number, item: any) => sum + Number(item.discount_amount || 0), 0);
                const totalAmount = subtotal + taxAmount - discountAmount;

                receiptData.value.receiptNumber = `RCP-${order.id}`;
                receiptData.value.date = order.created_at;
                receiptData.value.tableNumber = order.table_room?.name || "N/A";
                receiptData.value.cashierName = order.cashier?.name || "Unknown";
                receiptData.value.orderType = (order as any).order_type || "dine-in";
                receiptData.value.orderItems = mappedOrderItems;
                receiptData.value.subtotal = subtotal;
                receiptData.value.taxAmount = taxAmount;
                receiptData.value.discountAmount = discountAmount;
                receiptData.value.totalAmount = totalAmount;
                receiptData.value.paymentInfo = (order as any).payment_info || null;
            } else {
                // Fallback to sample data if order not found
                loadSampleData();
            }
        } catch (error) {
            console.error('Error fetching order:', error);
            // Fallback to sample data
            loadSampleData();
        }
    }
};

// Load sample data
const loadSampleData = () => {
    receiptData.value.orderItems = [
        {
            id: 1,
            name: "Chicken Joy",
            quantity: 2,
            unit_price: 85.0,
            price: 170.0,
            selected_options: [
                { id: 1, name: "Extra Rice", price: 15.0 },
                { id: 2, name: "Regular Drink", price: 20.0 },
            ],
            discount: 0,
        },
        {
            id: 2,
            name: "Tuna Pie",
            quantity: 1,
            unit_price: 45.0,
            price: 45.0,
            selected_options: [],
            discount: 5.0,
        },
    ];

    // Calculate totals
    const subtotal = receiptData.value.orderItems.reduce(
        (sum, item) => sum + item.price,
        0
    );
    const discountAmount = receiptData.value.orderItems.reduce(
        (sum, item) => sum + (item.discount || 0),
        0
    );
    const discountedSubtotal = subtotal - discountAmount;
    const taxAmount = discountedSubtotal * 0.12; // 12% VAT
    const totalAmount = discountedSubtotal + taxAmount;

    receiptData.value.subtotal = subtotal;
    receiptData.value.discountAmount = discountAmount;
    receiptData.value.taxAmount = taxAmount;
    receiptData.value.totalAmount = totalAmount;

    receiptData.value.paymentInfo = {
        amount_paid: 350.0,
        change: 350.0 - totalAmount,
        method: "Cash",
    };
};

// Print function
const printReceipt = () => {
    window.print();
};

// Go back to cashier
const goBack = () => {
    router.visit(route("retail-cashier.index"));
};

onMounted(() => {
    loadReceiptData();
});
</script>

<style>
@media print {
    body * {
        visibility: hidden;
    }
    .receipt-container,
    .receipt-container * {
        visibility: visible;
    }
    .receipt-container {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        max-width: none;
    }
}
</style>
